// @ts-nocheck
import { default as __fd_glob_63 } from "../content/docs/builder/builder/canvas/workflows/meta.json?collection=docs"
import { default as __fd_glob_62 } from "../content/docs/builder/builder/canvas/components/meta.json?collection=docs"
import { default as __fd_glob_61 } from "../content/docs/builder/builder/wizard/meta.json?collection=docs"
import { default as __fd_glob_60 } from "../content/docs/builder/builder/canvas/meta.json?collection=docs"
import { default as __fd_glob_59 } from "../content/docs/builder/usage/meta.json?collection=docs"
import { default as __fd_glob_58 } from "../content/docs/builder/dev/meta.json?collection=docs"
import { default as __fd_glob_57 } from "../content/docs/builder/ai/meta.json?collection=docs"
import { default as __fd_glob_56 } from "../content/docs/builder/builder/meta.json?collection=docs"
import { default as __fd_glob_55 } from "../content/docs/app/xml-processing/meta.json?collection=docs"
import { default as __fd_glob_54 } from "../content/docs/app/user-guides/meta.json?collection=docs"
import { default as __fd_glob_53 } from "../content/docs/app/model-schema/meta.json?collection=docs"
import { default as __fd_glob_52 } from "../content/docs/app/dev/meta.json?collection=docs"
import { default as __fd_glob_51 } from "../content/docs/app/database/meta.json?collection=docs"
import { default as __fd_glob_50 } from "../content/docs/builder/meta.json?collection=docs"
import { default as __fd_glob_49 } from "../content/docs/app/meta.json?collection=docs"
import * as __fd_glob_48 from "../content/docs/builder/builder/canvas/workflows/workflow-overview.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/builder/builder/canvas/workflows/tools-overview.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/builder/builder/canvas/workflows/actions-overview.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/builder/builder/canvas/components/tool-editor.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/builder/builder/canvas/components/relationship-editor.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/builder/builder/canvas/components/node-editor.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/builder/builder/canvas/components/model-builder.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/builder/builder/canvas/components/action-editor.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/builder/builder/wizard/wizard-overview.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/builder/user/introduction.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/builder/usage/model-schema-creation.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/builder/usage/graph-generation.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/builder/dev/workflow-system.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/builder/dev/types.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/builder/dev/state-management.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/builder/dev/services-layer.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/builder/dev/design-patterns.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/builder/dev/architecture-overview.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/builder/dev/ai-integration.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/builder/ai/xml-rules-assistant.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/builder/ai/xml-mapping-assistant.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/builder/ai/workflow-generation-agent.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/builder/ai/schema-design-agent.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/builder/ai/research-assistant-streaming.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/builder/ai/research-assistant-agent.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/builder/ai/relationship-recommendation-agent.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/builder/ai/node-property-suggestion-agent.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/app/xml-processing/xml-import.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/app/xml-processing/generate-graph.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/app/user-guides/roles-and-permissions.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/app/user-guides/getting-started.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/app/user-guides/dashboard.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/app/model-schema/model-schema-import.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/app/model-schema/create-model-schema.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/app/dev/workflow-system.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/app/dev/state-management.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/app/dev/services-layer.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/app/dev/module-system.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/app/dev/design-patterns.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/app/dev/database-models.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/app/dev/architecture.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/app/dev/architecture-overview.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/app/dev/ai-integration.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/app/database/querying.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/app/database/graph-analytics.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/app/database/database-management.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/builder/index.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/app/index.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/app/faq.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"app/meta.json": __fd_glob_49, "builder/meta.json": __fd_glob_50, "app/database/meta.json": __fd_glob_51, "app/dev/meta.json": __fd_glob_52, "app/model-schema/meta.json": __fd_glob_53, "app/user-guides/meta.json": __fd_glob_54, "app/xml-processing/meta.json": __fd_glob_55, "builder/builder/meta.json": __fd_glob_56, "builder/ai/meta.json": __fd_glob_57, "builder/dev/meta.json": __fd_glob_58, "builder/usage/meta.json": __fd_glob_59, "builder/builder/canvas/meta.json": __fd_glob_60, "builder/builder/wizard/meta.json": __fd_glob_61, "builder/builder/canvas/components/meta.json": __fd_glob_62, "builder/builder/canvas/workflows/meta.json": __fd_glob_63, }, {"app/faq.mdx": __fd_glob_0, "app/index.mdx": __fd_glob_1, "builder/index.mdx": __fd_glob_2, "app/database/database-management.mdx": __fd_glob_3, "app/database/graph-analytics.mdx": __fd_glob_4, "app/database/querying.mdx": __fd_glob_5, "app/dev/ai-integration.mdx": __fd_glob_6, "app/dev/architecture-overview.mdx": __fd_glob_7, "app/dev/architecture.mdx": __fd_glob_8, "app/dev/database-models.mdx": __fd_glob_9, "app/dev/design-patterns.mdx": __fd_glob_10, "app/dev/module-system.mdx": __fd_glob_11, "app/dev/services-layer.mdx": __fd_glob_12, "app/dev/state-management.mdx": __fd_glob_13, "app/dev/workflow-system.mdx": __fd_glob_14, "app/model-schema/create-model-schema.mdx": __fd_glob_15, "app/model-schema/model-schema-import.mdx": __fd_glob_16, "app/user-guides/dashboard.mdx": __fd_glob_17, "app/user-guides/getting-started.mdx": __fd_glob_18, "app/user-guides/roles-and-permissions.mdx": __fd_glob_19, "app/xml-processing/generate-graph.mdx": __fd_glob_20, "app/xml-processing/xml-import.mdx": __fd_glob_21, "builder/ai/node-property-suggestion-agent.mdx": __fd_glob_22, "builder/ai/relationship-recommendation-agent.mdx": __fd_glob_23, "builder/ai/research-assistant-agent.mdx": __fd_glob_24, "builder/ai/research-assistant-streaming.mdx": __fd_glob_25, "builder/ai/schema-design-agent.mdx": __fd_glob_26, "builder/ai/workflow-generation-agent.mdx": __fd_glob_27, "builder/ai/xml-mapping-assistant.mdx": __fd_glob_28, "builder/ai/xml-rules-assistant.mdx": __fd_glob_29, "builder/dev/ai-integration.mdx": __fd_glob_30, "builder/dev/architecture-overview.mdx": __fd_glob_31, "builder/dev/design-patterns.mdx": __fd_glob_32, "builder/dev/services-layer.mdx": __fd_glob_33, "builder/dev/state-management.mdx": __fd_glob_34, "builder/dev/types.mdx": __fd_glob_35, "builder/dev/workflow-system.mdx": __fd_glob_36, "builder/usage/graph-generation.mdx": __fd_glob_37, "builder/usage/model-schema-creation.mdx": __fd_glob_38, "builder/user/introduction.mdx": __fd_glob_39, "builder/builder/wizard/wizard-overview.mdx": __fd_glob_40, "builder/builder/canvas/components/action-editor.mdx": __fd_glob_41, "builder/builder/canvas/components/model-builder.mdx": __fd_glob_42, "builder/builder/canvas/components/node-editor.mdx": __fd_glob_43, "builder/builder/canvas/components/relationship-editor.mdx": __fd_glob_44, "builder/builder/canvas/components/tool-editor.mdx": __fd_glob_45, "builder/builder/canvas/workflows/actions-overview.mdx": __fd_glob_46, "builder/builder/canvas/workflows/tools-overview.mdx": __fd_glob_47, "builder/builder/canvas/workflows/workflow-overview.mdx": __fd_glob_48, });